#!/usr/bin/env python3
"""Entity definition table shared by the level compiler and the engine."""
from entdef import ENTITIES, NAME2ID

# behaviours (must match the jump table in src/entities.s)
BEHAV = ["NONE", "WALKER", "SHOOTER", "FLYER", "HOPPER", "AMBUSH",
         "CRUSHER", "SOUND", "OBJECT", "SHOT", "PICKUP", "STATIC"]
B = {n: i for i, n in enumerate(BEHAV)}

# flag bits, mirroring constants.inc
EF_FACELEFT, EF_GROUNDED, EF_KICKABLE, EF_GRABBABLE = 0x01, 0x02, 0x04, 0x08
EF_ARMORED, EF_HEAVY, EF_HARMLESS, EF_PROJECTILE = 0x10, 0x20, 0x40, 0x80

#  name: (behaviour, hp, w, h, damage, flags, frames, palette, speed, shot)
DEF = {
    "SPEAR_GUARD":  ("WALKER",  2, 12, 22, 1, 0, 4, 1, 0x60, 0),
    "ARCHER":       ("SHOOTER", 1, 12, 22, 1, 0, 3, 1, 0x00, "ARROW"),
    "SHIELD_KNIGHT":("WALKER",  3, 14, 22, 1, EF_ARMORED, 3, 1, 0x48, 0),
    "PEASANT":      ("WALKER",  1, 10, 22, 0, EF_HARMLESS, 3, 1, 0xB0, 0),
    "CHICKEN":      ("HOPPER",  1, 10, 10, 0, EF_HARMLESS, 2, 3, 0x90, 0),
    "ROYAL_MAGE":   ("SHOOTER", 2, 12, 22, 2, 0, 3, 1, 0x00, "BOLT"),
    "TRAPPER":      ("WALKER",  2, 12, 22, 1, 0, 3, 1, 0x70, 0),
    "BEETLE":       ("WALKER",  2, 14, 12, 1, EF_ARMORED | EF_HEAVY, 2, 2, 0x50, 0),
    "CROW":         ("FLYER",   1, 12, 10, 1, 0, 2, 2, 0xA0, 0),
    "BALLISTA":     ("SHOOTER", 4, 28, 20, 2, EF_HEAVY, 2, 2, 0x00, "ARROW"),
    "GARGOYLE":     ("FLYER",   3, 16, 20, 2, EF_ARMORED, 2, 2, 0x80, 0),
    "DRONE":        ("FLYER",   2, 14, 12, 1, 0, 2, 2, 0xC0, 0),
    "HEEL_CLAMP":   ("AMBUSH",  3, 20, 12, 2, EF_HEAVY, 2, 2, 0x00, 0),
    "TOE_CRUSHER":  ("CRUSHER", 255, 16, 30, 3, EF_HEAVY | EF_ARMORED, 2, 2, 0x00, 0),
    "BELL_MONK":    ("SOUND",   3, 12, 22, 2, 0, 3, 1, 0x40, "SPIT"),
    "KINGS_ELITE":  ("WALKER",  4, 14, 22, 2, EF_ARMORED, 3, 1, 0x68, 0),
    "LURKER":       ("AMBUSH",  2, 16, 14, 2, 0, 2, 2, 0x00, 0),
    "PIKE_TURRET":  ("SHOOTER", 3, 14, 14, 2, EF_HEAVY, 2, 2, 0x00, "SPIT"),

    "ROCK":         ("OBJECT",  1, 12, 12, 2, EF_KICKABLE | EF_GRABBABLE | EF_HARMLESS, 1, 3, 0, 0),
    "BARREL":       ("OBJECT",  1, 12, 14, 2, EF_KICKABLE | EF_GRABBABLE | EF_HARMLESS, 1, 3, 0, 0),
    "CANNONBALL":   ("OBJECT",  1, 10, 10, 3, EF_KICKABLE | EF_HARMLESS, 1, 3, 0, 0),
    "CRATE":        ("OBJECT",  1, 12, 12, 2, EF_KICKABLE | EF_GRABBABLE | EF_HARMLESS, 1, 3, 0, 0),
    "BOMB":         ("OBJECT",  1, 10, 10, 4, EF_KICKABLE | EF_GRABBABLE | EF_HARMLESS, 1, 3, 0, 0),

    "ARROW":        ("SHOT",    1, 12, 6, 1, EF_PROJECTILE, 1, 3, 0x0180, 0),
    "BOLT":         ("SHOT",    1, 8, 8, 2, EF_PROJECTILE, 2, 3, 0x00C0, 0),
    "SPIT":         ("SHOT",    1, 6, 6, 1, EF_PROJECTILE, 2, 3, 0x0140, 0),

    "HEALTH":       ("PICKUP",  1, 14, 14, 0, EF_HARMLESS, 1, 3, 0, 0),
    "SHOEBOX":      ("PICKUP",  1, 20, 16, 0, EF_HARMLESS, 1, 3, 0, 0),
    "LIFE":         ("PICKUP",  1, 12, 12, 0, EF_HARMLESS, 1, 3, 0, 0),
}


def build(write):
    n = len(ENTITIES)
    cols = {k: [0] * n for k in
            ("behav", "hp", "w", "h", "dmg", "flags", "frames", "pal",
             "spd_lo", "spd_hi", "shot")}
    for name, d in DEF.items():
        i = NAME2ID[name]
        beh, hp, w, h, dmg, flags, frames, pal, spd, shot = d
        cols["behav"][i] = B[beh]
        cols["hp"][i] = hp
        cols["w"][i] = w
        cols["h"][i] = h
        cols["dmg"][i] = dmg
        cols["flags"][i] = flags
        cols["frames"][i] = frames
        cols["pal"][i] = pal
        cols["spd_lo"][i] = spd & 0xFF
        cols["spd_hi"][i] = (spd >> 8) & 0xFF
        cols["shot"][i] = NAME2ID[shot] if shot else 0

    a = ["; Generated by tools/gen_entities.py -- do not edit.\n"]
    a.append(".segment \"B00\"\n")
    for k in cols:
        a.append(".export ed_%s\n" % k)
    for k, v in cols.items():
        a.append("ed_%s:\n" % k)
        for i in range(0, n, 12):
            a.append("        .byte " + ",".join("$%02X" % b for b in v[i:i + 12]) + "\n")
    write("entity_data.s", "".join(a))

    inc = ["; Generated by tools/gen_entities.py -- do not edit.\n"]
    for i, (nm, _) in enumerate(ENTITIES):
        inc.append("ET_%s = %d\n" % (nm, i))
    inc.append("ET_COUNT = %d\n" % n)
    for i, nm in enumerate(BEHAV):
        inc.append("BEH_%s = %d\n" % (nm, i))
    write("entities.inc", "".join(inc))
    return "entities: %d types\n" % n
