#!/usr/bin/env python3
"""Generate the ld65 linker configuration for BIG FOOT.

PRG: 256 KiB = 32 x 8 KiB banks (MMC3 / mapper 4)
     banks 0..29  -> switchable
       * banks 0..1 are linked for the $A000 window (R7)
       * banks 2..29 are linked for the $8000 window (R6)
     bank 30      -> fixed at $C000
     bank 31      -> fixed at $E000 (holds vectors)
CHR: 128 KiB = 128 x 1 KiB banks
"""
import os

A000_BANKS = 2          # banks linked at $A000
LAST = 31

out = []
out.append("# Generated by tools/gen_cfg.py -- do not edit by hand.\n")
out.append("MEMORY {\n")
out.append("    ZP:      start = $0000, size = $0100, type = rw, define = yes;\n")
out.append("    OAMBUF:  start = $0200, size = $0100, type = rw, define = yes;\n")
out.append("    RAM:     start = $0300, size = $0500, type = rw, define = yes;\n")
out.append("    HEADER:  start = $0000, size = $0010, type = ro, file = %O, fill = yes;\n")
for b in range(30):
    org = 0xA000 if b < A000_BANKS else 0x8000
    out.append("    PRG_%02d:  start = $%04X, size = $2000, type = ro, file = %%O, fill = yes, fillval = $FF;\n" % (b, org))
out.append("    PRG_30:  start = $C000, size = $2000, type = ro, file = %O, fill = yes, fillval = $FF;\n")
out.append("    PRG_31:  start = $E000, size = $1FFA, type = ro, file = %O, fill = yes, fillval = $FF;\n")
out.append("    VECTORS: start = $FFFA, size = $0006, type = ro, file = %O, fill = yes;\n")
out.append("    CHRROM:  start = $0000, size = $40000, type = ro, file = %O, fill = yes, fillval = $00;\n")
out.append("}\n\n")
out.append("SEGMENTS {\n")
out.append("    ZEROPAGE: load = ZP,      type = zp;\n")
out.append("    OAM:      load = OAMBUF,  type = bss, define = yes;\n")
out.append("    BSS:      load = RAM,     type = bss, define = yes;\n")
out.append("    HDR:      load = HEADER,  type = ro;\n")
for b in range(30):
    out.append("    B%02d:      load = PRG_%02d,  type = ro, optional = yes;\n" % (b, b))
out.append("    CODE2:    load = PRG_30,  type = ro, optional = yes;\n")
out.append("    RODATA2:  load = PRG_30,  type = ro, optional = yes;\n")
out.append("    CODE:     load = PRG_31,  type = ro;\n")
out.append("    RODATA:   load = PRG_31,  type = ro, optional = yes;\n")
out.append("    VECTORS:  load = VECTORS, type = ro;\n")
out.append("    CHARS:    load = CHRROM,  type = ro;\n")
out.append("}\n")

path = os.path.join(os.path.dirname(__file__), "..", "cfg", "big_foot.cfg")
with open(path, "w") as f:
    f.write("".join(out))
print("wrote", os.path.normpath(path))
