; Generated by tools/gen_ram.py -- do not edit.
.include "constants.inc"

.segment "ZEROPAGE"
.exportzp tmp0
tmp0: .res 1
.exportzp tmp1
tmp1: .res 1
.exportzp tmp2
tmp2: .res 1
.exportzp tmp3
tmp3: .res 1
.exportzp tmp4
tmp4: .res 1
.exportzp tmp5
tmp5: .res 1
.exportzp tmp6
tmp6: .res 1
.exportzp tmp7
tmp7: .res 1
.exportzp tmp8
tmp8: .res 1
.exportzp tmp9
tmp9: .res 1
.exportzp tmpA
tmpA: .res 1
.exportzp tmpB
tmpB: .res 1
.exportzp tmpC
tmpC: .res 1
.exportzp tmpD
tmpD: .res 1
.exportzp tmpE
tmpE: .res 1
.exportzp tmpF
tmpF: .res 1
.exportzp ptr0
ptr0: .res 2
.exportzp ptr1
ptr1: .res 2
.exportzp ptr2
ptr2: .res 2
.exportzp ptr3
ptr3: .res 2
.exportzp frame_count
frame_count: .res 1
.exportzp nmi_count
nmi_count: .res 1
.exportzp nmi_ready
nmi_ready: .res 1
.exportzp ppu_ctrl
ppu_ctrl: .res 1
.exportzp ppu_mask
ppu_mask: .res 1
.exportzp render_on
render_on: .res 1
.exportzp split_on
split_on: .res 1
.exportzp bank_8000
bank_8000: .res 1
.exportzp bank_save
bank_save: .res 1
.exportzp bank_a000
bank_a000: .res 1
.exportzp chr_bank_lo
chr_bank_lo: .res 1
.exportzp chr_bank_hi
chr_bank_hi: .res 1
.exportzp chr_bg0
chr_bg0: .res 1
.exportzp chr_bg1
chr_bg1: .res 1
.exportzp chr_bg2
chr_bg2: .res 1
.exportzp chr_bg3
chr_bg3: .res 1
.exportzp chr_dirty
chr_dirty: .res 1
.exportzp vram_len
vram_len: .res 1
.exportzp oam_idx
oam_idx: .res 1
.exportzp spr_x
spr_x: .res 2
.exportzp spr_y
spr_y: .res 1
.exportzp spr_attr
spr_attr: .res 1
.exportzp spr_flip
spr_flip: .res 1
.exportzp oam_hi
oam_hi: .res 1
.exportzp rng_lo
rng_lo: .res 1
.exportzp rng_hi
rng_hi: .res 1
.exportzp pad1
pad1: .res 1
.exportzp pad1_new
pad1_new: .res 1
.exportzp pad1_prev
pad1_prev: .res 1
.exportzp pad2
pad2: .res 1
.exportzp pad2_new
pad2_new: .res 1
.exportzp pad2_prev
pad2_prev: .res 1
.exportzp game_mode
game_mode: .res 1
.exportzp mode_next
mode_next: .res 1
.exportzp mode_timer
mode_timer: .res 1
.exportzp sub_state
sub_state: .res 1
.exportzp stage_num
stage_num: .res 1
.exportzp checkpoint
checkpoint: .res 1
.exportzp lives
lives: .res 1
.exportzp continues
continues: .res 1
.exportzp progress_flags
progress_flags: .res 1
.exportzp shoe_flags
shoe_flags: .res 1
.exportzp pause_flag
pause_flag: .res 1
.exportzp cam_x
cam_x: .res 2
.exportzp cam_x_max
cam_x_max: .res 2
.exportzp cam_y
cam_y: .res 1
.exportzp scroll_x
scroll_x: .res 1
.exportzp scroll_nt
scroll_nt: .res 1
.exportzp shake_timer
shake_timer: .res 1
.exportzp shake_amt
shake_amt: .res 1
.exportzp cam_lock
cam_lock: .res 1
.exportzp level_cols
level_cols: .res 2
.exportzp map_ptr
map_ptr: .res 2
.exportzp col_next
col_next: .res 2
.exportzp col_left
col_left: .res 2
.exportzp stream_side
stream_side: .res 1
.exportzp theme
theme: .res 1
.exportzp spawn_cur
spawn_cur: .res 1
.exportzp cur_ent
cur_ent: .res 1
.exportzp atk_x1
atk_x1: .res 2
.exportzp atk_x2
atk_x2: .res 2
.exportzp atk_y1
atk_y1: .res 1
.exportzp atk_y2
atk_y2: .res 1
.exportzp atk_dmg
atk_dmg: .res 1
.exportzp atk_kind
atk_kind: .res 1
.exportzp enemy_chr
enemy_chr: .res 1
.exportzp boss_chr
boss_chr: .res 1
.exportzp kick_type
kick_type: .res 1
.exportzp ent_tmp
ent_tmp: .res 1
.exportzp ent_tmp2
ent_tmp2: .res 1
.exportzp spawn_ptr
spawn_ptr: .res 2
.exportzp mt_ptr
mt_ptr: .res 2
.exportzp mt_tr
mt_tr: .res 2
.exportzp mt_bl
mt_bl: .res 2
.exportzp mt_br
mt_br: .res 2
.exportzp mt_at_p
mt_at_p: .res 2
.exportzp mt_fl_p
mt_fl_p: .res 2
.exportzp col_base
col_base: .res 2
.exportzp mtc_col
mtc_col: .res 2
.exportzp mtc_row
mtc_row: .res 1
.exportzp mtc_val
mtc_val: .res 1
.exportzp ms_lo_ptr
ms_lo_ptr: .res 2
.exportzp ms_hi_ptr
ms_hi_ptr: .res 2
.exportzp bms_lo_ptr
bms_lo_ptr: .res 2
.exportzp bms_hi_ptr
bms_hi_ptr: .res 2
.exportzp hdr_ptr
hdr_ptr: .res 2
.exportzp check_ptr
check_ptr: .res 2
.exportzp roster_ptr
roster_ptr: .res 2
.exportzp boss_col
boss_col: .res 2
.exportzp stream_state
stream_state: .res 1
.exportzp stream_col
stream_col: .res 2
.exportzp dmg_count
dmg_count: .res 1
.exportzp start_col
start_col: .res 2
.exportzp start_row
start_row: .res 1
.exportzp boss_id
boss_id: .res 1
.exportzp stage_shoe
stage_shoe: .res 1
.exportzp boss_music
boss_music: .res 1
.exportzp level_music
level_music: .res 1
.exportzp anim_bank
anim_bank: .res 1
.exportzp anim_timer
anim_timer: .res 1
.exportzp px
px: .res 2
.exportzp px_sub
px_sub: .res 1
.exportzp py
py: .res 2
.exportzp py_sub
py_sub: .res 1
.exportzp vx
vx: .res 2
.exportzp vy
vy: .res 2
.exportzp p_state
p_state: .res 1
.exportzp p_anim
p_anim: .res 1
.exportzp p_frame
p_frame: .res 1
.exportzp p_atimer
p_atimer: .res 1
.exportzp p_face
p_face: .res 1
.exportzp p_ground
p_ground: .res 1
.exportzp p_wasground
p_wasground: .res 1
.exportzp p_hp
p_hp: .res 1
.exportzp p_hp_max
p_hp_max: .res 1
.exportzp p_inv
p_inv: .res 1
.exportzp p_shoe
p_shoe: .res 1
.exportzp p_coyote
p_coyote: .res 1
.exportzp p_jumpbuf
p_jumpbuf: .res 1
.exportzp p_jumphold
p_jumphold: .res 1
.exportzp p_timer
p_timer: .res 1
.exportzp p_carry
p_carry: .res 1
.exportzp p_ground_type
p_ground_type: .res 1
.exportzp p_inwater
p_inwater: .res 1
.exportzp p_stompcharge
p_stompcharge: .res 1
.exportzp p_recoil
p_recoil: .res 1
.exportzp p_walkdist
p_walkdist: .res 1
.exportzp p_flash
p_flash: .res 1
.exportzp p_curframe
p_curframe: .res 1
.exportzp p_kickhit
p_kickhit: .res 1
.exportzp p_bounce
p_bounce: .res 1
.exportzp p_shoetimer
p_shoetimer: .res 1
.exportzp boss_active
boss_active: .res 1
.exportzp boss_hp
boss_hp: .res 1
.exportzp boss_maxhp
boss_maxhp: .res 1
.exportzp boss_phase
boss_phase: .res 1
.exportzp boss_timer
boss_timer: .res 1
.exportzp boss_state
boss_state: .res 1
.exportzp boss_flash
boss_flash: .res 1
.exportzp mus_song
mus_song: .res 1
.exportzp mus_speed
mus_speed: .res 1
.exportzp mus_fade
mus_fade: .res 1
.exportzp aud_tmp
aud_tmp: .res 1
.exportzp aud_ch
aud_ch: .res 1
.exportzp aud_reg
aud_reg: .res 1
.exportzp aud_vol
aud_vol: .res 1
.exportzp aud_note
aud_note: .res 1
.exportzp aud_bank
aud_bank: .res 1
.exportzp aud_busy
aud_busy: .res 1
.exportzp aud_p0
aud_p0: .res 2
.exportzp aud_p1
aud_p1: .res 2
.exportzp aud_p2
aud_p2: .res 2
.exportzp nmi_tmp
nmi_tmp: .res 1
.exportzp sc_ptr
sc_ptr: .res 2
.exportzp sc_wait
sc_wait: .res 1
.exportzp sc_hold
sc_hold: .res 1
.exportzp sc_count
sc_count: .res 1
.exportzp sc_row
sc_row: .res 1
.exportzp sc_bank
sc_bank: .res 1
.exportzp hud_dirty
hud_dirty: .res 1
.exportzp score
score: .res 3

.segment "OAM"
.export oam_buf
oam_buf: .res 256

.segment "BSS"
.export vram_buf
vram_buf: .res 176
.export oam_order
oam_order: .res 8
.export e_type
e_type: .res 12
.export e_state
e_state: .res 12
.export e_xl
e_xl: .res 12
.export e_xh
e_xh: .res 12
.export e_xs
e_xs: .res 12
.export e_yl
e_yl: .res 12
.export e_yh
e_yh: .res 12
.export e_ys
e_ys: .res 12
.export e_vxl
e_vxl: .res 12
.export e_vxh
e_vxh: .res 12
.export e_vyl
e_vyl: .res 12
.export e_vyh
e_vyh: .res 12
.export e_hp
e_hp: .res 12
.export e_tmr
e_tmr: .res 12
.export e_anim
e_anim: .res 12
.export e_frm
e_frm: .res 12
.export e_flags
e_flags: .res 12
.export e_hurt
e_hurt: .res 12
.export e_sub
e_sub: .res 12
.export e_slot
e_slot: .res 12
.export e_dir
e_dir: .res 12
.export pa_type
pa_type: .res 6
.export pa_xl
pa_xl: .res 6
.export pa_xh
pa_xh: .res 6
.export pa_y
pa_y: .res 6
.export pa_vx
pa_vx: .res 6
.export pa_vy
pa_vy: .res 6
.export pa_tmr
pa_tmr: .res 6
.export pa_frm
pa_frm: .res 6
.export spawn_used
spawn_used: .res 12
.export tile_dmg
tile_dmg: .res 24
.export column_buf
column_buf: .res 16
.export text_ptr
text_ptr: .res 2
.export text_x
text_x: .res 1
.export text_y
text_y: .res 1
.export text_delay
text_delay: .res 1
.export text_line
text_line: .res 1
.export password_buf
password_buf: .res 8
.export pw_cursor
pw_cursor: .res 1
.export ch_ordb
ch_ordb: .res 8
.export ch_ord
ch_ord: .res 8
.export ch_ptr
ch_ptr: .res 8
.export ch_wait
ch_wait: .res 4
.export ch_len
ch_len: .res 4
.export ch_instr
ch_instr: .res 4
.export ch_note
ch_note: .res 4
.export ch_vol
ch_vol: .res 4
.export ch_ep
ch_ep: .res 4
.export ch_ap
ch_ap: .res 4
.export ch_lasth
ch_lasth: .res 4
.export ch_on
ch_on: .res 4
.export ch_trig
ch_trig: .res 4
.export ch_static
ch_static: .res 4
.export sfxc_ptr
sfxc_ptr: .res 8
.export sfxc_pri
sfxc_pri: .res 4
.export sfxc_rep
sfxc_rep: .res 4
.export obj_state
obj_state: .res 16
.export boss_x
boss_x: .res 2
.export boss_y
boss_y: .res 2
.export boss_vx
boss_vx: .res 2
.export boss_vy
boss_vy: .res 2
.export boss_frm
boss_frm: .res 1
.export boss_sub
boss_sub: .res 1
.export boss_atk
boss_atk: .res 1
.export boss_dir
boss_dir: .res 1
.export boss_anchor
boss_anchor: .res 2
.export scratch
scratch: .res 32
